title: Muhammed Midlaj E V
logo: midlaj white bg.jpg
show_downloads: true
theme: jekyll-theme-minimal

description: >-
  Data Analyst | Supply Chain and Operations Analytics |
  Dubai, UAE | SQL, Power BI, Tableau, Excel, Google Sheets
